name: HNUCriclebook

on:
  push:
    branches:
      - main  # 배포를 수행할 브랜치 이름을 여기에 입력합니다.

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'  # 설치할 Flutter 버전을 여기에 입력합니다.

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Install Fastlane
        run: gem install fastlane -N

      - name: Deploy with Fastlane
        env:
          FASTLANE_LANE: 'release'
        run: fastlane $FASTLANE_LANE
